"""empty message

Revision ID: dc0d7896107f
Revises: 
Create Date: 2026-02-26 00:57:51.574458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dc0d7896107f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deuda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correo_proveedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('producto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock_pendiente', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pagada', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_serie', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('precio_compra', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('fecha_creacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_factura', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('producto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contrasena_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('domicilio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('recovery_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('transaccion')
    op.drop_table('producto')
    op.drop_table('movimiento')
    op.drop_table('deuda')
    # ### end Alembic commands ###
